[bot]
chat_id=-1001921297748
[data]
notify_delay=172800 # IN SECONDS (2 days current)
dates = {"–ú–µ—Å—è—Ü"=2592000}
one_price = 1000
[skins]
'https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Head%20Shot%20%28Battle-Scarred%29'=10
'https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Legion%20of%20Anubis%20%28Well-Worn%29'=9
'https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20AWP%20%7C%20Duality%20%28Field-Tested%29'=10
'https://steamcommunity.com/market/listings/730/AWP%20%7C%20Chromatic%20Aberration%20%28Well-Worn%29'=10
'https://steamcommunity.com/market/listings/730/Desert%20Eagle%20%7C%20Conspiracy%20%28Factory%20New%29'=8
'https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Nightmare%20%28Field-Tested%29'=10
'https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Desolate%20Space%20%28Minimal%20Wear%29'=10
'https://steamcommunity.com/market/listings/730/P2000%20%7C%20Imperial%20Dragon%20%28Factory%20New%29'=10
'https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20Tec-9%20%7C%20Fuel%20Injector%20%28Field-Tested%29'=7
'https://steamcommunity.com/market/listings/730/USP-S%20%7C%20Cortex%20%28Minimal%20Wear%29'=4
'https://steamcommunity.com/market/listings/730/%E2%98%85%20Hand%20Wraps%20%7C%20Giraffe%20%28Field-Tested%29'=100
'https://steamcommunity.com/market/listings/730/%E2%98%85%20Hydra%20Gloves%20%7C%20Case%20Hardened%20%28Battle-Scarred%29'=100
'https://steamcommunity.com/market/listings/730/%E2%98%85%20Classic%20Knife%20%7C%20Safari%20Mesh%20%28Field-Tested%29'=120
[texts]
start="–ü—Ä–∏–≤–µ—Ç—Å—Ç–≤—É—é –≤ –º–µ–Ω—é –±–æ—Ç–∞"
kick_now="–í—Ä–µ–º—è –≤—ã—à–ª–æ, –≤—ã –∏—Å–∫–ª—é—á–µ–Ω—ã –∏–∑ –≥—Ä—É–ø–ø—ã."
notify_now=""
invite_link="{link}"
buy_vip="–•–æ—Ç–∏—Ç–µ –ø–æ–ª—É—á–∏—Ç—å —Å–∫–∏–¥–∫—É –Ω–∞ –ø–æ–∫—É–ø–∫—É VIP-–∫–∞–Ω–∞–ª–∞ –∑–∞ –±–∞–ª–ª—ã?\n(—Å–∫–∏–¥–∫–∞ –∞–∫—Ç–∏–≤–∏—Ä—É–µ—Ç—Å—è —Å—Ä–∞–∑—É –ø–æ–ª—Å–ª–µ –Ω–∞–∂–∞—Ç–∏—è –∫–Ω–æ–ø–∫–∏)"
buy_vup_button="–ü–æ–ª—É—á–∏—Ç—å —Å–∫–∏–¥–∫—É N –±–∞–ª–ª–æ–≤"
success="–°–ø–∞—Å–∏–±–æ –∑–∞ –ø–æ–∫—É–ø–∫—É ü§ë\n–ü–µ—Ä–µ—Ö–æ–¥–∏—Ç–µ –∫ @jastie777\n–ò –∑–∞–±–∏—Ä–∞–π —Å–≤–æ—é –ø–æ–∫—É–ø–∫—É üî•"
unsuccess="–£ –≤–∞—Å –Ω–µ–¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –±–∞–ª–ª–æ–≤ –¥–ª—è –ø–æ–∫—É–ø–∫–∏ –¥–∞–Ω–Ω–æ–≥–æ —Ç–æ–≤–∞—Ä–∞. –£–≤—ã:("
account="–ü—Ä–∏–≤–µ—Ç, {user_name}\n–°—á—ë—Ç: {points} –±–∞–ª–ª–æ–≤"
buy_vip_menu='–ö—É–ø–∏—Ç—å –∫—É–ø–æ–Ω –Ω–∞ VIP-–∫–∞–Ω–∞–ª'

